theme: jekyll-theme-minimal
title: Cinnak
description: Writing and sharing about data science, AI, cybersecurity, and enjoying some great craft beersğŸºğŸ». Join me for some tech talk and beer chats!
markdown: kramdown
kramdown:
  input: GFM
