# ç«™ç‚¹è®¾ç½®
title: Cinnak's Blog
description: Writing and sharing about data science, AI, cybersecurity, and enjoying some craft beersğŸ». Join me for some tech talk and beer chats!
name: "Cinnak"
repository: "cinnak/cinnak.github.io"

# ä¸»é¢˜è®¾ç½®
theme: minima
minima_skin: "classic"

# ç«™ç‚¹é…ç½®
locale: "zh-CN"
search: true
atomfeed: true

# SEOç›¸å…³
url: "https://cinnak.github.io"
baseurl: ""

# ä½œè€…ä¿¡æ¯
author:
  name: "Cinnak"
  avatar: ""
  bio: "Cybersecurity and Technology Enthusiast"
  location: "Earth,Solar System, Local Interstellar Cloud,Local Bubble,Gould Belt,Orion Arm,Milky Way Galaxy,Local Group,Virgo Supercluster,Universe."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cinnak"

# é»˜è®¤å¸ƒå±€è®¾ç½®
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

# åˆ†é¡µè®¾ç½®
paginate: 5
paginate_path: /page:num/

# æ’ä»¶è®¾ç½®
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Uncomment and customize the following section if you want to add social links
# minima:
#   social_links:
#     - { platform: github,         user_url: "https://github.com/yourusername" }
#     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/yourusername" }
#     - { platform: twitter,        user_url: "https://twitter.com/yourusername" }
