theme: minima
title: Cinnak
description: Writing and sharing about data science, AI, cybersecurity, and enjoying some craft beersğŸºğŸ». Join me for some tech talk and beer chats!
markdown: kramdown
kramdown:
  input: GFM
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
